name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "RE4"
  comment: "Resident Evil 4 "
  url: "http://dl.coolrom.com.au/dl/41800/b_ZvyWpuGGQnF71_ZUvGGA/1609687941/"
  file_name: "ROM RESIDENT EVIL 4"
  piece_size: 19 # 2^21
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
